#!/usr/bin/env bash
# Script that displays information about subdomains using dig and awk

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    record_type=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION:/{getline; print $4}')
    destination=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION:/{getline; print $5}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi
